
// console.log('start')

// function setTimeout() {
//     console.log("таймер на 2 секунды")
// }

// window.setTimeout(function()) {
//     console.log("функция выполнена")
// }, 2000
// )
//  setTimeout(timeOut2sec,2000)


// //промисы
// let promise = new Promise(function(resolve,reject){
// //эта функция выполниться автоматически, когда будет называться new Pomise
// setTimeout(() => reject(new error("Ошибка")),1000);

// });


// promise.then(
//     result => akert(result)
//     result => akert(error)

// )
// function delay(ms) {
//     return new Promise(resolve => setTimeout(ms))
// }
//  delay(3000).then(() => alert('выполнилось через 3 секунды'))



// let helloPromise = new Promise(function(resolve)) {
//     resolve("Hello(успешное выполнение)")
// })

// let worldPromise = helloPromise(function(value)) {
//     return value + "world"
// })


// let academy  = academyPromise.then(function(value)) {
//     return value + "academy"
// })

// academy.then(function(finaValue){
//     console,log(finaValue)
// })


// new Promise(resolve => resolve("hello"))
// then(value => value +  "World")
// then(value => value +  "Academy")
// then(final => console.log(final))


//обработка  ошибок catch()















{
    "users:[
    {
        "id":1 
}